name: openapitodart
description: Code generation tool for OpenAPI to client dart
version: 0.0.2
homepage: https://github.com/tkfinitefield/openapitodart
repository: https://github.com/tkfinitefield/openapitodart

executables:
  openapitodart: main

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  args: ^2.3.0
  dart_style: ^2.2.1
  yaml: ^3.1.0

